In [ ]:
# Create a list of different data types

In [ ]:
l = ["Hello", 2, 4.67, "sslo", 354646, 345.332, bool, None, "Agaain Hello"]
print(l[3])

sslo


In [ ]:
t = tuple(l)

In [10]:
l1 = [20, 10, 25, 30, 40 ,50]

l2 = [1,2,3,4,5]

l3 = [l1]+ [l2]

print(l3)

print(l3[1][3])

[[20, 10, 25, 30, 40, 50], [1, 2, 3, 4, 5]]
4


In [17]:
import numpy as np

npArray = np.array(l1)
print(npArray)
print(type(npArray))

[20 10 25 30 40 50]
<class 'numpy.ndarray'>


In [22]:
v1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(v1 + 5)
print(v1 * 2)
print(v1[1:5])
print(v1[::-1])
print(v1[0:5:-1])




[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
[]


In [25]:
s = [[1,2,3], [3,4,5],[5,6,7]]
s1 = np.array(s)

print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])

print([[s1], [s1]])


[3 4 5]
[5 6 7]
[5 6 7]
4
5
[[array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])], [array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])]]


In [35]:
m1 = [[1,2,3],[4,5,6],[7,8,9]]
m2 = [[1,2,3],[4,5,6],[7,8,9]]

m1 = np.array(m1)
m2 = np.array(m2)

for i in range(len(m1)):
  for j in range(len(m2)):
    print(i, j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [36]:
# Matriz Multiplication
print(m1 @ m2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
